# For Fleet Free: 
# - This file updates policies, queries, agent_options, and controls for all hosts.

# For Fleet Premium:
# - This file updates policies and queries that run on all hosts ("All teams"). 
# - Remove "controls" and add this to your YAML files in teams/ instead.

policies:
  path: ./lib/windows-device-health.policies.yml
queries:
  path: ./lib/queries/pre-install-query.yml
agent_options:
  path: ./lib/agent-options.yml
controls:
org_settings:
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: Fleet
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
  features:
    enable_host_users: true
    enable_software_inventory: true
  sso_settings:
    enable_jit_provisioning: true
    enable_sso: true
    enable_sso_idp_login: true
    entity_id: fleetsso
    idp_image_url: ""
    idp_name: Okta
    metadata: 
    metadata_url: "https://dev-66479709.okta.com/app/exknouxjb8ILG2lM95d7/sso/saml/metadata"
  mdm:
    apple_business_manager:
    - organization_name: Fleet Device Management Inc.
    volume_purchasing_program:
    - location: Janis Watts
      teams:
      - "Workstations"
      - "Team1"
      - "Team2"
      - "Team3"
      - "Test-FMA"
labels:
  - path: ./lib/all/labels/test1.yml
  - path: ./lib/all/labels/design_label.yml
  - path: ./lib/all/labels/sales_label.yml
