description: Runs fleetctl gitops to apply configuration to Fleet
inputs:
  delete-other-teams:
    default: "true"
    description: Whether to delete other teams in Fleet which are not part of the gitops config.
  dry-run-only:
    default: "false"
    description: Whether to only run the fleetctl gitops commands in dry-run mode.
  working-directory:
    default: ./
    description: The working directory, which should be the root of the fleet-gitops repository.
name: fleetctl-gitops
runs:
  steps:
    - name: Install fleetctl
      run: |
        FLEET_VERSION="$(curl "$FLEET_URL/api/v1/fleet/version" --header "Authorization: Bearer $FLEET_API_TOKEN" --fail --silent | jq --raw-output '.version')"

        if [[ -n "$FLEET_VERSION" ]] ; then
          npm install -g "fleetctl@$FLEET_VERSION" || npm install -g fleetctl
        else
          echo "Failed to get Fleet version from $FLEET_URL, installing latest version of fleetctl"
          npm install -g fleetctl
        fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Configure fleetctl
      run: fleetctl config set --address ${{ env.FLEET_URL }} --token ${{ env.FLEET_API_TOKEN }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - env:
        FLEET_DELETE_OTHER_TEAMS: ${{ inputs.delete-other-teams }}
        FLEET_DRY_RUN_ONLY: ${{ inputs.dry-run-only }}
      name: Run fleetctl gitops commands
      run: ./gitops.sh
      shell: bash
      working-directory: ${{ inputs.working-directory }}
  using: composite
