concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}
defaults:
  run:
    shell: bash
jobs:
  fleet-gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v4
      - env:
          FLEET_API_TOKEN: ${{ secrets.FLEET_API_TOKEN }}
          FLEET_GLOBAL_ENROLL_SECRET: ${{ secrets.FLEET_GLOBAL_ENROLL_SECRET }}
          FLEET_TEST_FMA_ENROLL_SECRET: ${{ secrets.FLEET_TEST_FMA_ENROLL_SECRET }}
          FLEET_URL: ${{ secrets.FLEET_URL }}
          FLEET_WORKSTATIONS_CANARY_ENROLL_SECRET: ${{ secrets.FLEET_WORKSTATIONS_CANARY_ENROLL_SECRET }}
          FLEET_WORKSTATIONS_ENROLL_SECRET: ${{ secrets.FLEET_WORKSTATIONS_ENROLL_SECRET }}
        name: Apply latest configuration to Fleet
        uses: ./.github/gitops-action
        with:
          dry-run-only: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
name: Apply latest configuration to Fleet
"on":
  pull_request: null
  push:
    branches:
      - main
  workflow_dispatch: null
permissions:
  contents: read
